(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Tutorial",
  Authors -> {"C. Duhr"},
  Version -> "1.0",
  Date -> "27. 02. 2012",
  Institutions -> {"ETH Zurich"},
  Emails -> {"duhrc@itp.phys.ethz.ch"}};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], p1 -> S[4], p2 -> S[5], uv -> F[13], ev -> F[14]};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MPe1,
    Indices -> {},
    PropagatorLabel -> "p1" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MPe2,
    Indices -> {},
    PropagatorLabel -> "p2" },

F[13] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Y)/3, (2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Muv,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "uv" },

F[14] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Y, -Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mev,
    Indices -> {},
    PropagatorLabel -> "ev" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ S[4] ] = GaugeXi[S[102]];
GaugeXi[ S[5] ] = GaugeXi[S[103]];
GaugeXi[ F[13] ] = GaugeXi[F[100]];
GaugeXi[ F[14] ] = GaugeXi[F[101]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MTA[ ___ ] := MTA;
MT[ ___ ] := MT;
MB[ ___ ] := MB;
MH[ ___ ] := MH;
MPe1[ ___ ] := MPe1;
MPe2[ ___ ] := MPe2;
Muv[ ___ ] := Muv;
Mev[ ___ ] := Mev;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ F[13, {__}] ] := TheLabel[F[13]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{I*EL, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] ] == {{0, I*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, (-I)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc13, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc14, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc16, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc19, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc20, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc22, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc24, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc27, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc28, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc30, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc32, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc34, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[13, {e1x2}] , F[13, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{uv, uv}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{uv, uv}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*(2*FR$delta[{Muv}, {}] + Muv*FR$deltaZ[{uv, uv}, {{}}, "L"] + Muv*FR$deltaZ[{uv, uv}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*(2*FR$delta[{Muv}, {}] + Muv*FR$deltaZ[{uv, uv}, {{}}, "L"] + Muv*FR$deltaZ[{uv, uv}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc37*SUNF[e3x2, e1x1, e2x1], -(GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/(2*aS)}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), -(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc39*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {(-I)*gc39*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc39*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}},

C[ -F[14] , F[14] , V[1] ] == {{I*gc40, 0}, {I*gc40, 0}},

C[ -F[13, {e1x2}] , F[13, {e2x2}] , V[1] ] == {{I*gc41*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{uv, uv}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc41*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{uv, uv}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[13, {e2x2}] , S[5] ] == {{I*gc42*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam12*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]]*Cos[th] + lam13*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*Cos[th] + lam11*Cos[th]*FR$deltaZ[{u, u}, {{}}, "R"] + lam11*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] + lam22*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]]*Sin[th] + lam23*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*Sin[th] + lam21*FR$deltaZ[{u, u}, {{}}, "R"]*Sin[th] + lam21*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}, {0, 0}},

C[ -F[8, {e1x2}] , F[13, {e2x2}] , S[5] ] == {{I*gc43*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam13*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*Cos[th] + lam11*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]]*Cos[th] + lam12*Cos[th]*FR$deltaZ[{c, c}, {{}}, "R"] + lam12*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] + lam23*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*Sin[th] + lam21*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]]*Sin[th] + lam22*FR$deltaZ[{c, c}, {{}}, "R"]*Sin[th] + lam22*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}, {0, 0}},

C[ -F[9, {e1x2}] , F[13, {e2x2}] , S[5] ] == {{I*gc44*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam12*Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]]*Cos[th] + lam11*Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]]*Cos[th] + lam13*Cos[th]*FR$deltaZ[{t, t}, {{}}, "R"] + lam13*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] + lam22*Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]]*Sin[th] + lam21*Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]]*Sin[th] + lam23*FR$deltaZ[{t, t}, {{}}, "R"]*Sin[th] + lam23*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}, {0, 0}},

C[ -F[4] , F[14] , S[5] ] == {{I*gc45, 0}, {0, 0}},

C[ -F[5] , F[14] , S[5] ] == {{I*gc46, 0}, {0, 0}},

C[ -F[6] , F[14] , S[5] ] == {{I*gc47, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[13, {e2x2}] , S[4] ] == {{I*gc48*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam22*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]]*Cos[th] + lam23*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*Cos[th] + lam21*Cos[th]*FR$deltaZ[{u, u}, {{}}, "R"] + lam21*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] - lam12*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]]*Sin[th] - lam13*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*Sin[th] - lam11*FR$deltaZ[{u, u}, {{}}, "R"]*Sin[th] - lam11*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}, {0, 0}},

C[ -F[8, {e1x2}] , F[13, {e2x2}] , S[4] ] == {{I*gc49*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam23*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*Cos[th] + lam21*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]]*Cos[th] + lam22*Cos[th]*FR$deltaZ[{c, c}, {{}}, "R"] + lam22*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] - lam13*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*Sin[th] - lam11*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]]*Sin[th] - lam12*FR$deltaZ[{c, c}, {{}}, "R"]*Sin[th] - lam12*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}, {0, 0}},

C[ -F[9, {e1x2}] , F[13, {e2x2}] , S[4] ] == {{I*gc50*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam22*Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]]*Cos[th] + lam21*Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]]*Cos[th] + lam23*Cos[th]*FR$deltaZ[{t, t}, {{}}, "R"] + lam23*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] - lam12*Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]]*Sin[th] - lam11*Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]]*Sin[th] - lam13*FR$deltaZ[{t, t}, {{}}, "R"]*Sin[th] - lam13*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}, {0, 0}},

C[ -F[4] , F[14] , S[4] ] == {{I*gc51, 0}, {0, 0}},

C[ -F[5] , F[14] , S[4] ] == {{I*gc52, 0}, {0, 0}},

C[ -F[6] , F[14] , S[4] ] == {{I*gc53, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc54L*IndexDelta[e1x2, e2x2], (yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MB)}, {gc54R*IndexDelta[e1x2, e2x2], -(yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MT)}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{0, (yb*FR$deltaZ[{t, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/2}, {0, -(yt*FR$deltaZ[{t, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/2}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{0, (yb*FR$deltaZ[{t, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/2}, {0, -(yt*FR$deltaZ[{t, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/2}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc57L*IndexDelta[e1x2, e2x2], -(yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MB)}, {gc57R*IndexDelta[e1x2, e2x2], (yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MB)}},

C[ -F[12, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{0, -(yb*FR$deltaZ[{b, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {0, (yb*FR$deltaZ[{b, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[12, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{0, -(yb*FR$deltaZ[{b, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {0, (yb*FR$deltaZ[{b, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc60*IndexDelta[e1x2, e2x2], ((-I/2)*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {I*gc60*IndexDelta[e1x2, e2x2], ((-I/2)*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}},

C[ -F[12, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{0, ((-I/2)*yb*FR$deltaZ[{b, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {0, ((-I/2)*yb*FR$deltaZ[{b, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[12, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{0, ((-I/2)*yb*FR$deltaZ[{b, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {0, ((-I/2)*yb*FR$deltaZ[{b, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[10, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] + FR$deltaZ[{b, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, b}, {{}}, "R"]] + FR$deltaZ[{b, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MB*FR$deltaZ[{b, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MB*FR$deltaZ[{b, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[11, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] + FR$deltaZ[{b, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, b}, {{}}, "R"]] + FR$deltaZ[{b, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MB*FR$deltaZ[{b, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MB*FR$deltaZ[{b, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[6] , F[3] , -S[3] ] == {{gc66, 0}, {0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc67L, 0}, {gc67R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc68, 0}, {I*gc68, 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc69L*IndexDelta[e1x2, e2x2], (yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MT)}, {gc69R*IndexDelta[e1x2, e2x2], -(yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MT)}},

C[ -F[9, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{0, (yt*FR$deltaZ[{t, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {0, -(yt*FR$deltaZ[{t, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[9, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{0, (yt*FR$deltaZ[{t, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {0, -(yt*FR$deltaZ[{t, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc72*IndexDelta[e1x2, e2x2], ((-I/2)*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}, {I*gc72*IndexDelta[e1x2, e2x2], ((-I/2)*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[9, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{0, ((-I/2)*yt*FR$deltaZ[{t, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {0, ((-I/2)*yt*FR$deltaZ[{t, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[9, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{0, ((-I/2)*yt*FR$deltaZ[{t, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {0, ((-I/2)*yt*FR$deltaZ[{t, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[8, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] + FR$deltaZ[{t, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]] + FR$deltaZ[{t, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MT*FR$deltaZ[{t, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MT*FR$deltaZ[{t, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[7, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] + FR$deltaZ[{t, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]] + FR$deltaZ[{t, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MT*FR$deltaZ[{t, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MT*FR$deltaZ[{t, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc78L*IndexDelta[e1x2, e2x2], (yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MT)}, {gc78R*IndexDelta[e1x2, e2x2], -(yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MB)}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{0, (yt*FR$deltaZ[{b, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/2}, {0, -(yb*FR$deltaZ[{b, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/2}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{0, (yt*FR$deltaZ[{b, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/2}, {0, -(yb*FR$deltaZ[{b, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/2}},

C[ -F[8, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{0, (yt*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {0, -(yt*Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[7, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{0, (yt*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {0, -(yt*Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[8, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{0, ((-I/2)*yt*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {0, ((-I/2)*yt*Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[7, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{0, ((-I/2)*yt*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {0, ((-I/2)*yt*Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[8, {e1x2}] , F[9, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] + FR$deltaZ[{c, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]] + FR$deltaZ[{c, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MT*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MT*Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[9, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] + FR$deltaZ[{u, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]] + FR$deltaZ[{u, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MT*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MT*Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{0, (yt*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/2}, {0, -(yb*Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/2}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{0, (yt*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/2}, {0, -(yb*Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/2}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{0, (yb*Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/2}, {0, -(yt*Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/2}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{0, (yb*Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/2}, {0, -(yt*Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/2}},

C[ -F[10, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{0, -(yb*Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {0, (yb*Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[11, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{0, -(yb*Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {0, (yb*Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[10, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{0, ((-I/2)*yb*Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {0, ((-I/2)*yb*Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[11, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{0, ((-I/2)*yb*Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]]*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {0, ((-I/2)*yb*Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]]*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[10, {e1x2}] , F[12, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] + FR$deltaZ[{d, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]] + FR$deltaZ[{d, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MB*Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MB*Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[12, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] + FR$deltaZ[{s, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]] + FR$deltaZ[{s, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MB*Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*MB*Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]]*IndexDelta[e1x2, e2x2]}},

C[ -F[13, {e1x2}] , F[7, {e2x2}] , S[5] ] == {{0, 0}, {I*gc97R*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam12*Cos[th]*FR$deltaZ[{c, u}, {{}}, "R"] + lam13*Cos[th]*FR$deltaZ[{t, u}, {{}}, "R"] + lam11*Cos[th]*FR$deltaZ[{u, u}, {{}}, "R"] + lam11*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] + lam22*FR$deltaZ[{c, u}, {{}}, "R"]*Sin[th] + lam23*FR$deltaZ[{t, u}, {{}}, "R"]*Sin[th] + lam21*FR$deltaZ[{u, u}, {{}}, "R"]*Sin[th] + lam21*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}},

C[ -F[13, {e1x2}] , F[8, {e2x2}] , S[5] ] == {{0, 0}, {I*gc98R*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam12*Cos[th]*FR$deltaZ[{c, c}, {{}}, "R"] + lam13*Cos[th]*FR$deltaZ[{t, c}, {{}}, "R"] + lam11*Cos[th]*FR$deltaZ[{u, c}, {{}}, "R"] + lam12*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] + lam22*FR$deltaZ[{c, c}, {{}}, "R"]*Sin[th] + lam23*FR$deltaZ[{t, c}, {{}}, "R"]*Sin[th] + lam21*FR$deltaZ[{u, c}, {{}}, "R"]*Sin[th] + lam22*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}},

C[ -F[13, {e1x2}] , F[9, {e2x2}] , S[5] ] == {{0, 0}, {I*gc99R*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam12*Cos[th]*FR$deltaZ[{c, t}, {{}}, "R"] + lam13*Cos[th]*FR$deltaZ[{t, t}, {{}}, "R"] + lam11*Cos[th]*FR$deltaZ[{u, t}, {{}}, "R"] + lam13*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] + lam22*FR$deltaZ[{c, t}, {{}}, "R"]*Sin[th] + lam23*FR$deltaZ[{t, t}, {{}}, "R"]*Sin[th] + lam21*FR$deltaZ[{u, t}, {{}}, "R"]*Sin[th] + lam23*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}},

C[ -F[13, {e1x2}] , F[7, {e2x2}] , S[4] ] == {{0, 0}, {I*gc100R*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam22*Cos[th]*FR$deltaZ[{c, u}, {{}}, "R"] + lam23*Cos[th]*FR$deltaZ[{t, u}, {{}}, "R"] + lam21*Cos[th]*FR$deltaZ[{u, u}, {{}}, "R"] + lam21*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] - lam12*FR$deltaZ[{c, u}, {{}}, "R"]*Sin[th] - lam13*FR$deltaZ[{t, u}, {{}}, "R"]*Sin[th] - lam11*FR$deltaZ[{u, u}, {{}}, "R"]*Sin[th] - lam11*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}},

C[ -F[13, {e1x2}] , F[8, {e2x2}] , S[4] ] == {{0, 0}, {I*gc101R*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam22*Cos[th]*FR$deltaZ[{c, c}, {{}}, "R"] + lam23*Cos[th]*FR$deltaZ[{t, c}, {{}}, "R"] + lam21*Cos[th]*FR$deltaZ[{u, c}, {{}}, "R"] + lam22*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] - lam12*FR$deltaZ[{c, c}, {{}}, "R"]*Sin[th] - lam13*FR$deltaZ[{t, c}, {{}}, "R"]*Sin[th] - lam11*FR$deltaZ[{u, c}, {{}}, "R"]*Sin[th] - lam12*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}},

C[ -F[13, {e1x2}] , F[9, {e2x2}] , S[4] ] == {{0, 0}, {I*gc102R*IndexDelta[e1x2, e2x2], (I/2)*IndexDelta[e1x2, e2x2]*(lam22*Cos[th]*FR$deltaZ[{c, t}, {{}}, "R"] + lam23*Cos[th]*FR$deltaZ[{t, t}, {{}}, "R"] + lam21*Cos[th]*FR$deltaZ[{u, t}, {{}}, "R"] + lam23*Cos[th]*FR$deltaZ[{uv, uv}, {{}}, "L"] - lam12*FR$deltaZ[{c, t}, {{}}, "R"]*Sin[th] - lam13*FR$deltaZ[{t, t}, {{}}, "R"]*Sin[th] - lam11*FR$deltaZ[{u, t}, {{}}, "R"]*Sin[th] - lam13*FR$deltaZ[{uv, uv}, {{}}, "L"]*Sin[th])}},

C[ -F[14] , F[4] , S[5] ] == {{0, 0}, {I*gc103R, 0}},

C[ -F[14] , F[5] , S[5] ] == {{0, 0}, {I*gc104R, 0}},

C[ -F[14] , F[6] , S[5] ] == {{0, 0}, {I*gc105R, 0}},

C[ -F[14] , F[4] , S[4] ] == {{0, 0}, {I*gc106R, 0}},

C[ -F[14] , F[5] , S[4] ] == {{0, 0}, {I*gc107R, 0}},

C[ -F[14] , F[6] , S[4] ] == {{0, 0}, {I*gc108R, 0}},

C[ -F[13, {e1x2}] , F[13, {e2x2}] , V[4, {e3x2}] ] == {{I*gc109*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{uv, uv}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc109*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{uv, uv}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ S[2] , -S[3] , V[3] ] == {{((-I/2)*EL)/sw, 0}},

C[ -S[3] , S[1] , V[3] ] == {{EL/(2*sw), 0}},

C[ V[1] , V[3] , -V[3] ] == {{I*EL, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{((I/2)*EL)/sw, 0}},

C[ S[3] , S[1] , -V[3] ] == {{EL/(2*sw), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-2*I)*gc125, 0}, {I*gc125, 0}, {I*gc125, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(I*cw*EL)/sw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-2*I)*gc127, 0}, {I*gc127, 0}, {I*gc127, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc128R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{(EL*(cw^2 + sw^2))/(2*cw*sw), 0}},

C[ S[3] , -S[3] , V[2] ] == {{((I/2)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ -F[14] , F[14] , V[2] ] == {{I*gc132, 0}, {I*gc132, 0}},

C[ -F[13, {e1x2}] , F[13, {e2x2}] , V[2] ] == {{I*gc133*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{uv, uv}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/cw}, {I*gc133*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{uv, uv}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*vev)/(2*cw), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc140, 0}, {(-I)*gc140, 0}, {(2*I)*gc140, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-2*I)*gc145, 0}, {I*gc145, 0}, {I*gc145, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc146, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc147, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc148, 0}, {0, 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc149, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc150, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc151, 0}, {0, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc152, 0}, {I*gc152, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc153, 0}, {I*gc153, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc154, 0}, {I*gc154, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc155, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc156, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc157, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc158L, 0}, {I*gc158R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc159L, 0}, {I*gc159R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc160L, 0}, {I*gc160R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc161*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc161*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc162*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc162*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc163*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc163*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc166*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc166*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc167*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc167*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc168*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc168*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc169*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc170*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc171*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc172L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc172R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc173L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc173R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc174L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc174R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[8, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{0, (I/3)*EL*(Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] + FR$deltaZ[{c, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/3)*EL*(Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]] + FR$deltaZ[{c, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{0, (I/3)*EL*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/3)*EL*(Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + FR$deltaZ[{c, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{0, (I/3)*EL*(Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] + FR$deltaZ[{t, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/3)*EL*(Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]] + FR$deltaZ[{t, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{0, (I/3)*EL*(Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] + FR$deltaZ[{t, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/3)*EL*(Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]] + FR$deltaZ[{t, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{0, (I/3)*EL*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/3)*EL*(Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + FR$deltaZ[{u, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{0, (I/3)*EL*(Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] + FR$deltaZ[{u, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/3)*EL*(Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]] + FR$deltaZ[{u, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[7, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + FR$deltaZ[{c, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[8, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + FR$deltaZ[{u, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] + FR$deltaZ[{c, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]] + FR$deltaZ[{c, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + FR$deltaZ[{c, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] + FR$deltaZ[{t, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]] + FR$deltaZ[{t, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] + FR$deltaZ[{t, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]] + FR$deltaZ[{t, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + FR$deltaZ[{u, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] + FR$deltaZ[{u, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]] + FR$deltaZ[{u, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{0, ((I/12)*EL*(3*cw^2 - sw^2)*(Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] + FR$deltaZ[{c, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((-I/3)*EL*sw*(Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]] + FR$deltaZ[{c, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[8, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{0, ((I/12)*EL*(3*cw^2 - sw^2)*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((-I/3)*EL*sw*(Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + FR$deltaZ[{c, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{0, ((I/12)*EL*(3*cw^2 - sw^2)*(Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] + FR$deltaZ[{t, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((-I/3)*EL*sw*(Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]] + FR$deltaZ[{t, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{0, ((I/12)*EL*(3*cw^2 - sw^2)*(Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] + FR$deltaZ[{t, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((-I/3)*EL*sw*(Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]] + FR$deltaZ[{t, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{0, ((I/12)*EL*(3*cw^2 - sw^2)*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((-I/3)*EL*sw*(Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + FR$deltaZ[{u, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{0, ((I/12)*EL*(3*cw^2 - sw^2)*(Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] + FR$deltaZ[{u, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((-I/3)*EL*sw*(Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]] + FR$deltaZ[{u, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] + FR$deltaZ[{s, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] + FR$deltaZ[{b, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] + FR$deltaZ[{b, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] + FR$deltaZ[{d, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc201*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc201*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc202*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc202*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc203*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc203*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc206*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc206*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc207*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc207*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc208*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc208*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc209*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc210*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc211*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc212L*IndexDelta[e1x2, e2x2], ((-I/6)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc212R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc213L*IndexDelta[e1x2, e2x2], ((-I/6)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc213R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc214L*IndexDelta[e1x2, e2x2], ((-I/6)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc214R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] + FR$deltaZ[{t, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] + FR$deltaZ[{t, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] + FR$deltaZ[{u, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] + FR$deltaZ[{c, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{0, ((I/2)*EL*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{0, (-I/6)*EL*(Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] + FR$deltaZ[{b, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (-I/6)*EL*(Conjugate[FR$deltaZ[{d, b}, {{}}, "R"]] + FR$deltaZ[{b, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{0, (-I/6)*EL*(Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] + FR$deltaZ[{b, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (-I/6)*EL*(Conjugate[FR$deltaZ[{s, b}, {{}}, "R"]] + FR$deltaZ[{b, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{0, (-I/6)*EL*(Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] + FR$deltaZ[{d, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (-I/6)*EL*(Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]] + FR$deltaZ[{d, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{0, (-I/6)*EL*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (-I/6)*EL*(Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + FR$deltaZ[{d, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{0, (-I/6)*EL*(Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] + FR$deltaZ[{s, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (-I/6)*EL*(Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]] + FR$deltaZ[{s, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{0, (-I/6)*EL*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (-I/6)*EL*(Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + FR$deltaZ[{s, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[11, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + FR$deltaZ[{d, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[10, {e2x2}] ] == {{0, (-I/2)*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + FR$deltaZ[{s, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] + FR$deltaZ[{b, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{d, b}, {{}}, "R"]] + FR$deltaZ[{b, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] + FR$deltaZ[{b, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{s, b}, {{}}, "R"]] + FR$deltaZ[{b, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] + FR$deltaZ[{d, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]] + FR$deltaZ[{d, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + FR$deltaZ[{d, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] + FR$deltaZ[{s, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]] + FR$deltaZ[{s, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + FR$deltaZ[{s, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{0, ((-I/12)*EL*(3*cw^2 + sw^2)*(Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] + FR$deltaZ[{b, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((I/6)*EL*sw*(Conjugate[FR$deltaZ[{d, b}, {{}}, "R"]] + FR$deltaZ[{b, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[12, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{0, ((-I/12)*EL*(3*cw^2 + sw^2)*(Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] + FR$deltaZ[{b, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((I/6)*EL*sw*(Conjugate[FR$deltaZ[{s, b}, {{}}, "R"]] + FR$deltaZ[{b, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{0, ((-I/12)*EL*(3*cw^2 + sw^2)*(Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] + FR$deltaZ[{d, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((I/6)*EL*sw*(Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]] + FR$deltaZ[{d, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{0, ((-I/12)*EL*(3*cw^2 + sw^2)*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((I/6)*EL*sw*(Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + FR$deltaZ[{d, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{0, ((-I/12)*EL*(3*cw^2 + sw^2)*(Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] + FR$deltaZ[{s, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((I/6)*EL*sw*(Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]] + FR$deltaZ[{s, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{0, ((-I/12)*EL*(3*cw^2 + sw^2)*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(cw*sw)}, {0, ((I/6)*EL*sw*(Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + FR$deltaZ[{s, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/cw}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc13 -> -EL,
     gc14 -> EL,
     gc16 -> -EL,
     gc19 -> EL,
     gc20 -> (cw*EL)/sw,
     gc22 -> -((cw*EL)/sw),
     gc24 -> EL,
     gc27 -> -EL,
     gc28 -> -((cw*EL)/sw),
     gc30 -> (cw*EL)/sw,
     gc32 -> -((cw*EL)/sw),
     gc34 -> (cw*EL)/sw,
     gc37 -> -GS,
     gc39 -> GS^2,
     gc40 -> -EL,
     gc41 -> (2*EL)/3,
     gc42 -> lam11*Cos[th] + lam21*Sin[th],
     gc43 -> lam12*Cos[th] + lam22*Sin[th],
     gc44 -> lam13*Cos[th] + lam23*Sin[th],
     gc45 -> lam1p1*Cos[th] + lam2p1*Sin[th],
     gc46 -> lam1p2*Cos[th] + lam2p2*Sin[th],
     gc47 -> lam1p3*Cos[th] + lam2p3*Sin[th],
     gc48 -> lam21*Cos[th] - lam11*Sin[th],
     gc49 -> lam22*Cos[th] - lam12*Sin[th],
     gc50 -> lam23*Cos[th] - lam13*Sin[th],
     gc51 -> lam2p1*Cos[th] - lam1p1*Sin[th],
     gc52 -> lam2p2*Cos[th] - lam1p2*Sin[th],
     gc53 -> lam2p3*Cos[th] - lam1p3*Sin[th],
     gc54L -> yb,
     gc54R -> -yt,
     gc57L -> -(yb/Sqrt[2]),
     gc57R -> yb/Sqrt[2],
     gc60 -> -(yb/Sqrt[2]),
     gc66 -> ytau,
     gc67L -> -(ytau/Sqrt[2]),
     gc67R -> ytau/Sqrt[2],
     gc68 -> -(ytau/Sqrt[2]),
     gc69L -> yt/Sqrt[2],
     gc69R -> -(yt/Sqrt[2]),
     gc72 -> -(yt/Sqrt[2]),
     gc78L -> yt,
     gc78R -> -yb,
     gc97R -> lam11*Cos[th] + lam21*Sin[th],
     gc98R -> lam12*Cos[th] + lam22*Sin[th],
     gc99R -> lam13*Cos[th] + lam23*Sin[th],
     gc100R -> lam21*Cos[th] - lam11*Sin[th],
     gc101R -> lam22*Cos[th] - lam12*Sin[th],
     gc102R -> lam23*Cos[th] - lam13*Sin[th],
     gc103R -> lam1p1*Cos[th] + lam2p1*Sin[th],
     gc104R -> lam1p2*Cos[th] + lam2p2*Sin[th],
     gc105R -> lam1p3*Cos[th] + lam2p3*Sin[th],
     gc106R -> lam2p1*Cos[th] - lam1p1*Sin[th],
     gc107R -> lam2p2*Cos[th] - lam1p2*Sin[th],
     gc108R -> lam2p3*Cos[th] - lam1p3*Sin[th],
     gc109 -> GS,
     gc125 -> EL^2,
     gc127 -> -(EL^2/sw^2),
     gc128R -> -ytau,
     gc132 -> (EL*sw)/cw,
     gc133 -> (-2*EL*sw)/(3*cw),
     gc140 -> -((cw*EL^2)/sw),
     gc145 -> (cw^2*EL^2)/sw^2,
     gc146 -> EL/(Sqrt[2]*sw),
     gc147 -> EL/(Sqrt[2]*sw),
     gc148 -> EL/(Sqrt[2]*sw),
     gc149 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc150 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc151 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc152 -> -EL,
     gc153 -> -EL,
     gc154 -> -EL,
     gc155 -> EL/(Sqrt[2]*sw),
     gc156 -> EL/(Sqrt[2]*sw),
     gc157 -> EL/(Sqrt[2]*sw),
     gc158L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc158R -> (EL*sw)/cw,
     gc159L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc159R -> (EL*sw)/cw,
     gc160L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc160R -> (EL*sw)/cw,
     gc161 -> (2*EL)/3,
     gc162 -> (2*EL)/3,
     gc163 -> (2*EL)/3,
     gc166 -> GS,
     gc167 -> GS,
     gc168 -> GS,
     gc169 -> EL/(Sqrt[2]*sw),
     gc170 -> EL/(Sqrt[2]*sw),
     gc171 -> EL/(Sqrt[2]*sw),
     gc172L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc172R -> (-2*EL*sw)/(3*cw),
     gc173L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc173R -> (-2*EL*sw)/(3*cw),
     gc174L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc174R -> (-2*EL*sw)/(3*cw),
     gc201 -> -EL/3,
     gc202 -> -EL/3,
     gc203 -> -EL/3,
     gc206 -> GS,
     gc207 -> GS,
     gc208 -> GS,
     gc209 -> EL/(Sqrt[2]*sw),
     gc210 -> EL/(Sqrt[2]*sw),
     gc211 -> EL/(Sqrt[2]*sw),
     gc212L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc212R -> (EL*sw)/(3*cw),
     gc213L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc213R -> (EL*sw)/(3*cw),
     gc214L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc214R -> (EL*sw)/(3*cw)};

